# Generated by Django 5.1.7 on 2025-03-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetgreetformapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fans',
            name='do_you_have_ticket_for_minhoverse',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='fans',
            name='if_yes_which_of_the_ticket_category_and_country_do_you_have',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
