# Generated by Django 5.1.7 on 2025-03-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetgreetformapp', '0002_fans_do_you_have_ticket_for_minhoverse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fans',
            name='payment_slip',
            field=models.FileField(blank=True, null=True, upload_to='payment_slips/'),
        ),
    ]
